# Generated by Django 4.0.3 on 2022-04-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=100)),
                ('csurname', models.CharField(max_length=100)),
                ('cphone', models.CharField(max_length=100)),
                ('ccity', models.CharField(max_length=100)),
                ('cdistrict', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
